apiVersion: apps/v1
kind: Deployment
metadata:
  name: use-k8s-secret
  labels:
    app: use-k8s-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: use-k8s-secret
  template:
    metadata:
      labels:
        app: use-k8s-secret
    spec:
      volumes:
      - name: tls-secret-volume
        secret:
          secretName: tls-secret
      - name: files-secret-volume
        secret:
          secretName: files-secret
      containers:
      - name: use-k8s-secret
        image: use-k8s-secret:latest
        # Use the local built image.
        imagePullPolicy: Never
        # Mount the secret.
        volumeMounts:
        - name: tls-secret-volume
          readOnly: true
          mountPath: "/etc/tls-secret-volume"
        - name: files-secret-volume
          readOnly: true
          mountPath: "/etc/files-secret-volume"
        ports:
        - containerPort: 8443
        env:
        - name: CERT_FILE
          value: "/etc/tls-secret-volume/tls.crt"
        - name: KEY_FILE
          value: "/etc/tls-secret-volume/tls.key"
        - name: SECRET1_FILE
          value: "/etc/files-secret-volume/secretfile1"
